In [2]:
import numpy as np


In [11]:
#list 
new_list=[-9,0,2]
new_list
type(new_list)

list

In [9]:
#array
my_array=np.array(new_list)
my_array

type(my_array)

numpy.ndarray

In [13]:
matrix=my_array+my_array
matrix

array([-18,   0,   4])

In [15]:
matrix_list= [[-9,0,2],[-9,0,2]]
matrix_list

[[-9, 0, 2], [-9, 0, 2]]

In [18]:
d_array=np.array(matrix_list)
d_array

array([[-9,  0,  2],
       [-9,  0,  2]])

In [19]:
d_array.shape


(2, 3)

In [20]:
num=np.arange(100)
num


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
nm=np.arange(1,20)
nm


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [24]:
n=np.arange(1,100,2)
n

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])