<h1>give random number using <b>rand()<b><h1> <br> <h6>randgives the number from 0-1</h6><br><h6>randint(start,end,koita number lagbe int) </h6>
    

In [1]:
import numpy as np
np.random.rand(5)

array([0.0603454 , 0.22843046, 0.46578761, 0.24694086, 0.85026407])

In [2]:
np.random.rand(6,4)

array([[0.60458554, 0.26712839, 0.5136931 , 0.25109487],
       [0.72363456, 0.39279977, 0.87439628, 0.71192372],
       [0.16477057, 0.10719035, 0.08997456, 0.80940494],
       [0.00690607, 0.79842187, 0.90469842, 0.71732125],
       [0.82636977, 0.90864838, 0.68561523, 0.42795741],
       [0.86916049, 0.885683  , 0.87371952, 0.6722828 ]])

In [3]:
np.random.randint(4,100,9)

array([37, 87, 45, 23, 87,  7, 82, 49,  9])

In [4]:
arr=np.random.randint(0,100,10)
arr

array([90, 90, 76, 54, 29, 52, 23, 63, 30,  3])

In [6]:
arr.min()


np.int64(3)

In [7]:
arr.max()

np.int64(90)

In [8]:
arr.argmax()

np.int64(0)

In [9]:
arr.argmin()

np.int64(9)

In [10]:
arr_1=np.array([3,2,4,1,9,8,7,6,5])
arr_1

array([3, 2, 4, 1, 9, 8, 7, 6, 5])

In [11]:
arr_1[1]


np.int64(2)

In [13]:
arr_1[0:4]

array([3, 2, 4, 1])

In [14]:
arr_1[-2]

np.int64(6)

In [15]:
arr_1


array([3, 2, 4, 1, 9, 8, 7, 6, 5])

In [16]:
arr_1[0]=-22


In [17]:
arr_1

array([-22,   2,   4,   1,   9,   8,   7,   6,   5])

In [19]:
arr_2d=np.arange(24)
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
arr_2d=arr_2d.reshape(6,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
arr_2d[2]

array([ 8,  9, 10, 11])

In [30]:
arr_2d[3,2]

np.int64(14)

In [31]:
arr_2d[:2,:2]

array([[0, 1],
       [4, 5]])