In [1]:
#import the numpy as np short
import numpy as np

In [2]:
#list print lekhar drkr nai
my_list=[-1,0,1]
my_list


[-1, 0, 1]

In [4]:
my_arr=np.array(my_list)
my_arr


array([-1,  0,  1])

In [5]:
type(my_arr)

numpy.ndarray

In [6]:
my_matrix=[[2,3,5,7],[1,4,6,8]]
my_matrix


[[2, 3, 5, 7], [1, 4, 6, 8]]

In [7]:
type(my_matrix)


list

In [8]:
matrix=np.array(my_matrix)
type(matrix)

numpy.ndarray

In [9]:
matrix


array([[2, 3, 5, 7],
       [1, 4, 6, 8]])

In [10]:
matrix*matrix


array([[ 4,  9, 25, 49],
       [ 1, 16, 36, 64]])

In [ ]:
matrix.shape


(2, 4)

In [5]:
import numpy as np


num = np.arange(100)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
#range ta divided kore
np.linspace(1,10,10,retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), np.float64(1.0))

In [16]:
x= np.array([2,3,4,5,7,6,4,3,2,1,4,5,5,11,12,13.])
x


array([ 2,  3,  4,  5,  7,  6,  4,  3,  2,  1,  4,  5,  5, 11, 12, 13])

In [18]:
x.shape

(16,)

In [19]:
x.reshape(4,4)

array([[ 2,  3,  4,  5],
       [ 7,  6,  4,  3],
       [ 2,  1,  4,  5],
       [ 5, 11, 12, 13]])

In [20]:
x.reshape(4,2,2)


array([[[ 2,  3],
        [ 4,  5]],

       [[ 7,  6],
        [ 4,  3]],

       [[ 2,  1],
        [ 4,  5]],

       [[ 5, 11],
        [12, 13]]])