In [1]:
#import the numpy as np short
import numpy as np

In [2]:
#list print lekhar drkr nai
my_list=[-1,0,1]
my_list


[-1, 0, 1]

In [4]:
my_arr=np.array(my_list)
my_arr


array([-1,  0,  1])

In [5]:
type(my_arr)

numpy.ndarray

In [6]:
my_matrix=[[2,3,5,7],[1,4,6,8]]
my_matrix


[[2, 3, 5, 7], [1, 4, 6, 8]]

In [7]:
type(my_matrix)


list

In [8]:
matrix=np.array(my_matrix)
type(matrix)

numpy.ndarray

In [9]:
matrix


array([[2, 3, 5, 7],
       [1, 4, 6, 8]])

In [10]:
matrix*matrix


array([[ 4,  9, 25, 49],
       [ 1, 16, 36, 64]])

In [ ]:
matrix.shape


(2, 4)